config/routes.rb
Rails.application.routes.draw do
  get '/streams/', to: 'streams#index', as: 'stream_index'
  get '/visitors/:id', to: 'visitors#index'
  root to: 'visitors#index'
end

app/models/stream.rb
require 'tweetstream'
class Stream
	
	TweetStream.configure do |config|  
	  config.consumer_key       = ENV["CONSUMER_KEY"]
	  config.consumer_secret    = ENV["CONSUMER_SECRET"]
	  config.oauth_token        = ENV["OAUTH_TOKEN"]
	  config.oauth_token_secret = ENV["OAUTH_TOKEN_SECRET"]
	  config.auth_method        = :oauth
	end  

	def do_stream
		Rails.logger.debug 'Doing Stream!'
		cuenta = 0
		@statuses
		TweetStream::Client.new.track('mom') do |status|
			cuenta += 1
			@statuses << status
			puts "#{cuenta} : #{status.text}"
			break if cuenta >= 5
		end  
		Rails.logger.debug 'STREAM FINISHED THANKS'
	end
end

app/models/visitor.rb
class Visitor
	def greeting
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
	def index
		@stream = Stream.new
		#render :stream => true
	end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	def index
		@visitor = Visitor.new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? "success" : "alert" %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 4 %>
<nav class="top-bar">
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%=link_to 'Stream', stream_index_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tweets Wave" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Tweets Wave" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/streams/index.html.erb
<% content_for :title do %>Stream<% end %>
<h3>Stream</h3>
<p>Hello!</p>
<% @stream.do_stream() %>

app/views/visitors/index.html.erb
<% content_for :title do %>Tweets-wave<% end %>
<h3>Home</h3>
<h4>Time in the server is: <%= Time.now%></h4>
<p>Welcome to the experimental tweet-wave project!</p>
<% @visitor.greeting() %>